#!/usr/bin/env python3
"""
Selects an optimal page layout (margins, font size, line spacing, vertical gaps)
based on the length and density of CV.md to ensure it fits on a single page.
"""

import argparse
import os
import re
import sys
from pathlib import Path

# Layout tiers configuration
TIERS = {
    'spacious': {
        'fontsize': '11pt',
        'margin': '0.6in',
        'linestretch': '1.25',
        'parskip': '0.8em',
        'section_pre_skip': '1.0em',
        'section_rule_skip': '-0.8em',
        'section_post_skip': '0.4em',
        'title_post_skip': '-0.4em',
        'job_pre_skip': '0.6em',
        'job_post_skip': '-0.1em',
        'itemsep': '3pt',
        'parsep': '2pt',
        'topsep': '4pt'
    },
    'standard': {
        'fontsize': '10pt',
        'margin': '0.5in',
        'linestretch': '1.15',
        'parskip': '0.6em',
        'section_pre_skip': '0.8em',
        'section_rule_skip': '-0.8em',
        'section_post_skip': '0.3em',
        'title_post_skip': '-0.6em',
        'job_pre_skip': '0.4em',
        'job_post_skip': '-0.2em',
        'itemsep': '2pt',
        'parsep': '1pt',
        'topsep': '3pt'
    },
    'compact': {
        'fontsize': '9.5pt',
        'margin': '0.45in',
        'linestretch': '1.05',
        'parskip': '0.35em',
        'section_pre_skip': '0.5em',
        'section_rule_skip': '-0.7em',
        'section_post_skip': '0.2em',
        'title_post_skip': '-0.8em',
        'job_pre_skip': '0.2em',
        'job_post_skip': '-0.3em',
        'itemsep': '1pt',
        'parsep': '0pt',
        'topsep': '1pt'
    },
    'tight': {
        'fontsize': '9pt',
        'margin': '0.35in',
        'linestretch': '0.95',
        'parskip': '0.2em',
        'section_pre_skip': '0.3em',
        'section_rule_skip': '-0.6em',
        'section_post_skip': '0.15em',
        'title_post_skip': '-1.0em',
        'job_pre_skip': '0.1em',
        'job_post_skip': '-0.4em',
        'itemsep': '0pt',
        'parsep': '0pt',
        'topsep': '0pt'
    }
}

TIER_ORDER = ['spacious', 'standard', 'compact', 'tight']

def get_current_tier_from_env_file(env_file_path):
    """Parse the existing pandoc_vars.env if it exists to get the active tier."""
    if not os.path.exists(env_file_path):
        return None
    try:
        with open(env_file_path, 'r', encoding='utf-8') as f:
            content = f.read()
            match = re.search(r'TIER=(\w+)', content)
            if match:
                return match.group(1)
    except Exception:
        pass
    return None

def analyze_cv(cv_content):
    """
    Analyze CV markdown to calculate a density score.
    Returns (word_count, bullet_count, section_count, score).
    """
    # Remove HTML comments if any
    cleaned_content = re.sub(r'<!--.*?-->', '', cv_content, flags=re.DOTALL)
    
    # Word count (words are characters separated by whitespace)
    words = cleaned_content.split()
    word_count = len(words)
    
    # Bullet points count
    bullets = re.findall(r'^\s*[-*+]\s+', cleaned_content, re.MULTILINE)
    bullet_count = len(bullets)
    
    # Section count (headers level 1, 2, 3)
    sections = re.findall(r'^#{1,3}\s+', cleaned_content, re.MULTILINE)
    section_count = len(sections)
    
    # Heuristic score for layout size selection:
    # A bullet point adds vertical space equivalent to ~6 words.
    # A header adds vertical space equivalent to ~12 words.
    score = word_count + (bullet_count * 6) + (section_count * 12)
    
    return word_count, bullet_count, section_count, score

def determine_tier(score):
    """Map the density score to a layout tier."""
    if score <= 400:
        return 'spacious'
    elif score <= 650:
        return 'standard'
    elif score <= 900:
        return 'compact'
    else:
        return 'tight'

def write_latex_vars(tier_data, output_path):
    """Write the LaTeX variable definitions file."""
    latex_content = f"""% Adaptive layout variables — generated by layout_optimizer.py
% Selected tier: {tier_data['name']}
\\newcommand{{\\cvParSkip}}{{{tier_data['parskip']}}}
\\newcommand{{\\cvTitlePostSkip}}{{{tier_data['title_post_skip']}}}
\\newcommand{{\\cvSectionPreSkip}}{{{tier_data['section_pre_skip']}}}
\\newcommand{{\\cvSectionRuleSkip}}{{{tier_data['section_rule_skip']}}}
\\newcommand{{\\cvSectionPostSkip}}{{{tier_data['section_post_skip']}}}
\\newcommand{{\\cvJobPreSkip}}{{{tier_data['job_pre_skip']}}}
\\newcommand{{\\cvJobPostSkip}}{{{tier_data['job_post_skip']}}}
\\newcommand{{\\cvItemSep}}{{{tier_data['itemsep']}}}
\\newcommand{{\\cvParSep}}{{{tier_data['parsep']}}}
\\newcommand{{\\cvTopSep}}{{{tier_data['topsep']}}}
"""
    dir_name = os.path.dirname(output_path)
    if dir_name:
        os.makedirs(dir_name, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(latex_content)

def write_env_vars(tier_data, output_path):
    """Write the env file containing variables for the workflow run."""
    env_content = f"""FONTSIZE={tier_data['fontsize']}
MARGIN={tier_data['margin']}
LINESTRETCH={tier_data['linestretch']}
TIER={tier_data['name']}
"""
    dir_name = os.path.dirname(output_path)
    if dir_name:
        os.makedirs(dir_name, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(env_content)


def main():
    parser = argparse.ArgumentParser(description="Optimize CV layout size dynamically.")
    parser.add_argument('--cv', default='CV.md', help="Path to CV.md")
    parser.add_argument('--output-tex', default='assets/layout_vars.tex', help="Path to output LaTeX vars file")
    parser.add_argument('--output-vars', default='pandoc_vars.env', help="Path to output env variables file")
    parser.add_argument('--tighten', action='store_true', help="Tighten layout by one tier from current state")
    parser.add_argument('--tier', choices=TIER_ORDER, help="Force a specific layout tier")
    
    args = parser.parse_args()
    
    if not os.path.exists(args.cv):
        print(f"Error: CV file not found at {args.cv}", file=sys.stderr)
        sys.exit(1)
        
    with open(args.cv, 'r', encoding='utf-8') as f:
        cv_content = f.read()
        
    word_count, bullet_count, section_count, score = analyze_cv(cv_content)
    
    selected_tier_name = None
    
    if args.tier:
        selected_tier_name = args.tier
        print(f"Forcing layout tier: {selected_tier_name}")
    elif args.tighten:
        # Get active tier from previous run
        current_tier = get_current_tier_from_env_file(args.output_vars)
        if current_tier:
            try:
                curr_idx = TIER_ORDER.index(current_tier)
                next_idx = min(curr_idx + 1, len(TIER_ORDER) - 1)
                selected_tier_name = TIER_ORDER[next_idx]
                print(f"Tightening layout from '{current_tier}' to '{selected_tier_name}'")
            except ValueError:
                selected_tier_name = 'tight'
        else:
            # Fallback to standard -> compact
            selected_tier_name = 'compact'
            print(f"No current tier found in {args.output_vars}, defaulting tightening to 'compact'")
    else:
        selected_tier_name = determine_tier(score)
        print(f"CV Analysis: {word_count} words, {bullet_count} bullets, {section_count} sections. Score: {score}")
        print(f"Auto-selected layout tier: '{selected_tier_name}'")
        
    tier_data = TIERS[selected_tier_name].copy()
    tier_data['name'] = selected_tier_name
    
    # Save the output files
    write_latex_vars(tier_data, args.output_tex)
    write_env_vars(tier_data, args.output_vars)
    
    print(f"✓ Wrote LaTeX vars to {args.output_tex}")
    print(f"✓ Wrote Env variables to {args.output_vars}")

if __name__ == '__main__':
    main()
